### ISSUE TITLE
[Feature] Add S3 Gateway endpoints to reduce the data processing cost of NAT gateway when loading models from S3 bucket

### ISSUE THREAD

**Issue by walkley** [aws-samples/stable-diffusion-on-eks#100]
**Is your feature request related to a problem? Please describe.**
For those model inference pods which are running in private subnets with NAT Gateway,  while loading models from S3 bucket, data processing fee will be charged with NAT Gateway. See [NAT Gateway pricing](https://aws.amazon.com/vpc/pricing/) for details.

**Describe the solution you'd like**
Use [S3 Gateway endpoints](https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html) will eliminate the data processing cost in NAT Gateway.

**Describe alternatives you've considered**
N/A

**Additional context**
This is the following up action after introduced mountpoint for S3 CSI (#81).

**Comment by yubingjiaocn** [comment]
Close as #104 implemented
