### ISSUE TITLE
[BUG] tmp folder is full when download model.

### ISSUE THREAD

**Issue by Chris-wa-He** [aws-samples/stable-diffusion-on-eks#103]
**What happened**:
tmp folder is full when download model.

**To Reproduce**
1.Create EC2 with Amazon Linux 2023
2.Install Git, Python, npm with yum
3.Run deploy.sh

Same issue when deploy with Cloud9

**Attach logs**
added 1 package in 2s
npm notice
npm notice New major version of npm available! 9.8.1 -> 10.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.0
npm notice Run npm install -g npm@10.5.0 to update!
npm notice
Tools install complete.
Step 2: Create S3 bucket and upload SD 1.5 model...
make_bucket: sdoneks-model-bucket-e273
Downloading SD 1.5 base model from hugging face...
curl: (23) Failure writing output to destination
[ec2-user@ip-172-31-37-102 deploy]$ df -hl
Filesystem        Size  Used Avail Use% Mounted on
devtmpfs          4.0M     0  4.0M   0% /dev
tmpfs             3.9G     0  3.9G   0% /dev/shm
tmpfs             1.6G  444K  1.6G   1% /run
/dev/nvme0n1p1     80G  2.8G   78G   4% /
tmpfs             3.9G  3.9G     0 100% /tmp
/dev/nvme0n1p128   10M  1.3M  8.7M  13% /boot/efi
tmpfs             782M     0  782M   0% /run/user/1000

**What you expected to happen**: deployment is completed without issue.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by yubingjiaocn** [comment]
Fixed in 749e278cb1ead07181a8adbc772889fea7b2a6ec
