### ISSUE TITLE
[BUG] multiple images can be generated in one task, but there is an error in X-ray tracking.

### ISSUE THREAD

**Issue by keithyt06** [aws-samples/stable-diffusion-on-eks#13]
**What happened**:
We have installed the Contrelnet plugin model in the /model directory. Now we need to use the WebUI API to generate multiple inference images. Due to the lack of program logic for parallel processing of multiple image tasks using X-ray (i.e., xray_recorder.begin_subsegment or xray_recorder.end_subsegment()), an error occurred, resulting in the inability to find the generated image URLs in response.out.

**To Reproduce**
=> Queue_agen Error Log
![image](https://github.com/aws-samples/stable-diffusion-on-eks/assets/103325445/8abaf177-43ed-4a9f-95cd-e18656289f18)

**Attach logs**
=> Response.Out Log
```
{
"images": [
""
],
"parameters": {
"id_task": "76-new",
"status": 0,
"image_url": "",
"seed": [],
"error_msg": "AlreadyEndedException('Already ended segment and subsegment cannot be modified.')",
"image_mask_url": ""
},
"info": ""
}
```

**What you expected to happen**:
- Optimize X-ray Tracing logic to allow me retrieve S3 URL from the output.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by 6congyao** [comment]
The fix had been merged, close it and follow-up.

**Comment by bnusunny** [comment]
The error still exits. This is a known issue with x-ray and `asyncio.gather()`. Need to find an alternative solution. 

https://github.com/aws/aws-xray-sdk-python/issues/164
