### ISSUE TITLE
[BUG]Webui and Queue Agent container insight metrics missing

### ISSUE THREAD

**Issue by brilliantwf** [aws-samples/stable-diffusion-on-eks#17]
**What happened**:
Unable view webui Queue agent pod/container related metrics in Cloudwatch Container insight.

**Comment by yubingjiaocn** [comment]
By default container insight scrape metrics by pod ([See docs here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-EKS.html)). `cadvisor` in `kubelet` provides container-level metrics, but need to manual scrape and send to CW. 

To scrape metrics by container, you can: 
* Customize container insights config file to allows more metrics to be scrape and sent to CW
* Use Prometheus or other self-hosted monitoring solutions to scrape all metrics.
