### ISSUE TITLE
[Feature] Add DCGM exporter to monitor GPU usage

### ISSUE THREAD

**Issue by yubingjiaocn** [aws-samples/stable-diffusion-on-eks#25]
**Describe the solution you'd like**
Add NVIDIA DCGM exporter to monitor GPU usage, and send metrics to Prometheus or CW container insight.

**Comment by keithyt06** [comment]
My Customer also raised the same feature demand during the implementation of the solution, requesting the addition of GPU utilization monitoring feature in CloudWatch.

**Comment by yubingjiaocn** [comment]
Working on a improvement to use NVIDIA Operator instead of NVDP, which will introduce DCGM exporter automatically.

**Comment by yubingjiaocn** [comment]
Close as #104 implemented
