### ISSUE TITLE
[Feature] Add output to a SNS topic or  Lambda example & md explain

### ISSUE THREAD

**Issue by keithyt06** [aws-samples/stable-diffusion-on-eks#39]
**Is your feature request related to a problem? Please describe.**
- Queue Agent sends output to a SNS topic and the application backend receives notification from Sos queue.
=> In the source code, it seems that there is no explanation for the output section.

**Describe the solution you'd like**
Add output to a SNS topic or  Lambda example & md explain

**Comment by yubingjiaocn** [comment]
We have a section covered how to subscribe to output SNS topic. https://aws-samples.github.io/stable-diffusion-on-eks/zh/implementation-guide/usage/callback/

**Comment by yubingjiaocn** [comment]
Update: Per discussion on Bug Bash, we can refer to customer's practice for organizing request and receives responses.

**Comment by yubingjiaocn** [comment]
Close as #104 implemented
