### ISSUE TITLE
[BUG] Incorrect model mount point causing model not found in the webui runtime

### ISSUE THREAD

**Issue by JianyuZhan** [aws-samples/stable-diffusion-on-eks#41]
Per the doc, the s3 layout is like:
└── models/
     ├── stable-diffusions
     ├── controlnet
     └── lora
i.e.  the modle dir is:  `models/stable-diffusions`

But the default mount point in the webui container is `/tmp/models`,  so after mouting, the actual model path is `/tmp/models/models/stable-diffusions`. 

The problem is: the webui is started with argument `-ckpt-dir /tmp/models/stable-diffusion`, so it complains no models found. Not only there is an extra `models` in the path, but also the model dir shall be `stable-diffusion` without a suffix `s`.

**Comment by bnusunny** [comment]
The "models" directory should not be used in S3. Could you share the link to the document where this is presented?

**Comment by yubingjiaocn** [comment]
Looks like it's related to https://github.com/aws-samples/stable-diffusion-on-eks/blob/main/docs/zh/implementation-guide/deployment/models.md . 

Fixing...
