### ISSUE TITLE
[Feature] Contains filename in the api resonse

### ISSUE THREAD

**Issue by ensean** [aws-samples/stable-diffusion-on-eks#45]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The response of the call to the APIGW should contains the final filename, only the path is included currently. Expected output

```json
{"id_task": "123", "task": "text-to-image", "sd_model_checkpoint": "v1-5-pruned-emaonly.safetensors", "output_location": "s3://sdoneksdataplanestack-outputs3bucket/123/20231116084316-fdcafa65-9990-42b7-b7ce-30bc2249d4d5.png"}

```

**Describe alternatives you've considered**

**Additional context**

**Comment by yubingjiaocn** [comment]
Close as not able to implement. We can't determine number and format of images for a request may generate.
