### ISSUE TITLE
[BUG] Helm Charts retrieval failed when deploying in China region

### ISSUE THREAD

**Issue by chenxqdu** [aws-samples/stable-diffusion-on-eks#53]
<img width="1389" alt="Screenshot 2023-11-22 at 13 20 53" src="https://github.com/aws-samples/stable-diffusion-on-eks/assets/107521997/6c6f290f-1c52-44d2-8685-afb9b7f6b83e">

**Comment by yubingjiaocn** [comment]
Got more report related to China region deployment. Bump to P0 and add doc to describe the issue.

**Comment by yubingjiaocn** [comment]
Close as #114
