### ISSUE TITLE
[BUG] Cannot Properly Deploy Pods

### ISSUE THREAD

**Issue by DoYouAlsoLikePotatoes** [aws-samples/stable-diffusion-on-eks#75]
**What happened**:
Trying to deploy the pods but they are in CrashLoopBackOff state. The pods are running in g5.xlarge instances.
dynamicsdruntime-sd-on-eks-sd-webui-inference-api-567d869748bls   2/3     CrashLoopBackOff   3 (1s ago)   4m29s
sdruntime1-sd-on-eks-sd-webui-inference-api-5b5d67c95f-blvbg      2/3     CrashLoopBackOff   3 (3s ago)   4m29s

Warning  FailedScheduling  5m32s                 default-scheduler  0/2 nodes are available: 2 Insufficient cpu, 2 Insufficient memory, 2 Insufficient nvidia.com/gpu. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..

I tried to increase the instance type but it didn't work out.

**Environment**:
Following the same config.yaml in [stable-diffusion-on-eks](https://github.com/aws-samples/stable-diffusion-on-eks/tree/main)
/config.yaml

**Comment by yubingjiaocn** [comment]
Hi, thank you for your response. Please attach log of SD Web UI in the issue so we can investigate into the issue. 

Also, could you please check if the model is properly synced to EFS? You can check it via AWS Console or mount EFS filesystem to a EC2 instance. If not, you may need to run DataSync task manually.

**Comment by yubingjiaocn** [comment]
Close stale issue. Feel free to reopen it if the issue persists.
